server.address=0.0.0.0
spring.application.name=TravelPlan
spring.data.mongodb.uri=mongodb+srv://ayazderaiya823:AyazDeraiya@clusterayaz.22vrc2f.mongodb.net/?retryWrites=true&w=majority&appName=ClusterAyaz
spring.data.mongodb.database=travelmind